DOMAIN = "radiator"
DEFAULT_PORT = 4815

CONF_HOST = "host"
CONF_PORT = "port"

# Radiator panel protocol controls
CTRL_PRESET_PAGE_ENCODER = 82
BTN_PRESET_1 = 20  # 20..29 are Preset 1..10

# Slot behavior
SLOT_COUNT = 20
PRESET_MIN = 1
PRESET_MAX = 1000

DEFAULT_INTERVAL_SECONDS = 10
INTERVAL_MIN_SECONDS = 1
INTERVAL_MAX_SECONDS = 3600
