"""Constants and OSC entity definitions for HARadiator."""
from __future__ import annotations

from dataclasses import dataclass
from typing import Final

DOMAIN: Final = "haradiator"

CONF_SEND_PORT: Final = "send_port"
CONF_LISTEN_HOST: Final = "listen_host"
CONF_LISTEN_PORT: Final = "listen_port"
CONF_PRESET_COUNT: Final = "preset_count"
CONF_EXPOSE_ADVANCED: Final = "expose_advanced"

DEFAULT_SEND_PORT: Final = 8000
DEFAULT_LISTEN_HOST: Final = "0.0.0.0"
DEFAULT_LISTEN_PORT: Final = 9000
DEFAULT_PRESET_COUNT: Final = 1000
DEFAULT_EXPOSE_ADVANCED: Final = False

PLATFORMS: Final = ["select", "sensor", "switch", "number"]

ATTR_ADDRESS: Final = "address"
ATTR_VALUE: Final = "value"

SERVICE_SEND_MESSAGE: Final = "send_message"


@dataclass(frozen=True, kw_only=True)
class RadiatorOscDescription:
    """Static description for one Radiator OSC endpoint."""

    key: str
    name: str
    address: str
    value_type: str
    direction: str
    section: str | None = None
    notes: str | None = None
    native_min_value: float | None = None
    native_max_value: float | None = None
    native_step: float | None = None
    entity_registry_enabled_default: bool = False

    # Home Assistant platform entities expect these attributes to exist on
    # entity_description. We do not use special device classes for Radiator yet.
    device_class: str | None = None
    entity_category: str | None = None
    icon: str | None = None

NUMBER_DESCRIPTIONS: Final[tuple[RadiatorOscDescription, ...]] = (
    RadiatorOscDescription(key='radiator_color_hue', name='Color Hue', address='/radiator/color/hue', value_type='float', direction='RX+TX', section='COLOR', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=True),
    RadiatorOscDescription(key='radiator_color_saturate', name='Color Saturate', address='/radiator/color/saturate', value_type='float', direction='RX+TX', section='COLOR', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=True),
    RadiatorOscDescription(key='radiator_color_value', name='Color Value', address='/radiator/color/value', value_type='float', direction='RX+TX', section='COLOR', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=True),
    RadiatorOscDescription(key='radiator_color_mod_p1', name='Color Mod P1', address='/radiator/color/mod/p1', value_type='float', direction='RX+TX', section='COLOR', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_color_mod_p2', name='Color Mod P2', address='/radiator/color/mod/p2', value_type='float', direction='RX+TX', section='COLOR', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_color_mod_p3', name='Color Mod P3', address='/radiator/color/mod/p3', value_type='float', direction='RX+TX', section='COLOR', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_color_mod_type', name='Color Mod Type', address='/radiator/color/mod/type', value_type='int', direction='RX+TX', section='COLOR', notes='Color mod type index', native_min_value=0.0, native_max_value=255, native_step=1, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_color_mode', name='Color Mode', address='/radiator/color/mode', value_type='int', direction='RX+TX', section='COLOR', notes='0=HSV  1=RGB  2=Custom  3=Gradient', native_min_value=0.0, native_max_value=3.0, native_step=1, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_color_z_depth', name='Color Z Depth', address='/radiator/color/z_depth', value_type='float', direction='RX', section='COLOR', notes='Z-depth color falloff amount', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_color_custom_hue_0', name='Color Custom Hue 0', address='/radiator/color/custom_hue/0', value_type='float', direction='RX', section='COLOR', notes='Custom hue slot 0', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_color_custom_hue_1', name='Color Custom Hue 1', address='/radiator/color/custom_hue/1', value_type='float', direction='RX', section='COLOR', notes='Custom hue slot 1', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_color_custom_hue_2', name='Color Custom Hue 2', address='/radiator/color/custom_hue/2', value_type='float', direction='RX', section='COLOR', notes='Custom hue slot 2', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_color_lfo1_h_level', name='Color LFO 1 H Level', address='/radiator/color/lfo1/h_level', value_type='float', direction='RX+TX', section='COLOR – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → hue depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_color_lfo2_h_level', name='Color LFO 2 H Level', address='/radiator/color/lfo2/h_level', value_type='float', direction='RX+TX', section='COLOR – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → hue depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_color_lfo3_h_level', name='Color LFO 3 H Level', address='/radiator/color/lfo3/h_level', value_type='float', direction='RX+TX', section='COLOR – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → hue depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_color_lfo1_s_level', name='Color LFO 1 S Level', address='/radiator/color/lfo1/s_level', value_type='float', direction='RX+TX', section='COLOR – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → saturation depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_color_lfo2_s_level', name='Color LFO 2 S Level', address='/radiator/color/lfo2/s_level', value_type='float', direction='RX+TX', section='COLOR – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → saturation depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_color_lfo3_s_level', name='Color LFO 3 S Level', address='/radiator/color/lfo3/s_level', value_type='float', direction='RX+TX', section='COLOR – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → saturation depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_color_lfo1_v_level', name='Color LFO 1 V Level', address='/radiator/color/lfo1/v_level', value_type='float', direction='RX+TX', section='COLOR – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → value depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_color_lfo2_v_level', name='Color LFO 2 V Level', address='/radiator/color/lfo2/v_level', value_type='float', direction='RX+TX', section='COLOR – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → value depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_color_lfo3_v_level', name='Color LFO 3 V Level', address='/radiator/color/lfo3/v_level', value_type='float', direction='RX+TX', section='COLOR – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → value depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_color_lfo1_mod1', name='Color LFO 1 Mod1', address='/radiator/color/lfo1/mod1', value_type='float', direction='RX+TX', section='COLOR – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → color mod P1 depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_color_lfo2_mod1', name='Color LFO 2 Mod1', address='/radiator/color/lfo2/mod1', value_type='float', direction='RX+TX', section='COLOR – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → color mod P1 depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_color_lfo3_mod1', name='Color LFO 3 Mod1', address='/radiator/color/lfo3/mod1', value_type='float', direction='RX+TX', section='COLOR – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → color mod P1 depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_color_lfo1_mod2', name='Color LFO 1 Mod2', address='/radiator/color/lfo1/mod2', value_type='float', direction='RX+TX', section='COLOR – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → color mod P2 depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_color_lfo2_mod2', name='Color LFO 2 Mod2', address='/radiator/color/lfo2/mod2', value_type='float', direction='RX+TX', section='COLOR – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → color mod P2 depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_color_lfo3_mod2', name='Color LFO 3 Mod2', address='/radiator/color/lfo3/mod2', value_type='float', direction='RX+TX', section='COLOR – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → color mod P2 depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_color_lfo1_mod3', name='Color LFO 1 Mod3', address='/radiator/color/lfo1/mod3', value_type='float', direction='RX+TX', section='COLOR – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → color mod P3 depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_color_lfo2_mod3', name='Color LFO 2 Mod3', address='/radiator/color/lfo2/mod3', value_type='float', direction='RX+TX', section='COLOR – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → color mod P3 depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_color_lfo3_mod3', name='Color LFO 3 Mod3', address='/radiator/color/lfo3/mod3', value_type='float', direction='RX+TX', section='COLOR – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → color mod P3 depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo1_warp', name='LFO 1 Warp', address='/radiator/lfo1/warp', value_type='float', direction='RX+TX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=True),
    RadiatorOscDescription(key='radiator_lfo2_warp', name='LFO 2 Warp', address='/radiator/lfo2/warp', value_type='float', direction='RX+TX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=True),
    RadiatorOscDescription(key='radiator_lfo3_warp', name='LFO 3 Warp', address='/radiator/lfo3/warp', value_type='float', direction='RX+TX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=True),
    RadiatorOscDescription(key='radiator_lfo1_warp_type', name='LFO 1 Warp Type', address='/radiator/lfo1/warp_type', value_type='int', direction='RX+TX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', notes='Warp type index', native_min_value=0.0, native_max_value=255, native_step=1, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo2_warp_type', name='LFO 2 Warp Type', address='/radiator/lfo2/warp_type', value_type='int', direction='RX+TX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', notes='Warp type index', native_min_value=0.0, native_max_value=255, native_step=1, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo3_warp_type', name='LFO 3 Warp Type', address='/radiator/lfo3/warp_type', value_type='int', direction='RX+TX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', notes='Warp type index', native_min_value=0.0, native_max_value=255, native_step=1, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo1_shape', name='LFO 1 Shape', address='/radiator/lfo1/shape', value_type='int', direction='RX+TX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO shape index', native_min_value=0.0, native_max_value=255, native_step=1, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo2_shape', name='LFO 2 Shape', address='/radiator/lfo2/shape', value_type='int', direction='RX+TX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO shape index', native_min_value=0.0, native_max_value=255, native_step=1, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo3_shape', name='LFO 3 Shape', address='/radiator/lfo3/shape', value_type='int', direction='RX+TX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO shape index', native_min_value=0.0, native_max_value=255, native_step=1, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo1_speed', name='LFO 1 Speed', address='/radiator/lfo1/speed', value_type='float', direction='RX+TX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=True),
    RadiatorOscDescription(key='radiator_lfo2_speed', name='LFO 2 Speed', address='/radiator/lfo2/speed', value_type='float', direction='RX+TX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=True),
    RadiatorOscDescription(key='radiator_lfo3_speed', name='LFO 3 Speed', address='/radiator/lfo3/speed', value_type='float', direction='RX+TX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=True),
    RadiatorOscDescription(key='radiator_lfo1_level', name='LFO 1 Level', address='/radiator/lfo1/level', value_type='float', direction='RX+TX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=True),
    RadiatorOscDescription(key='radiator_lfo2_level', name='LFO 2 Level', address='/radiator/lfo2/level', value_type='float', direction='RX+TX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=True),
    RadiatorOscDescription(key='radiator_lfo3_level', name='LFO 3 Level', address='/radiator/lfo3/level', value_type='float', direction='RX+TX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=True),
    RadiatorOscDescription(key='radiator_lfo1_phase', name='LFO 1 Phase', address='/radiator/lfo1/phase', value_type='float', direction='RX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO phase offset', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo2_phase', name='LFO 2 Phase', address='/radiator/lfo2/phase', value_type='float', direction='RX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO phase offset', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo3_phase', name='LFO 3 Phase', address='/radiator/lfo3/phase', value_type='float', direction='RX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO phase offset', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo1_cv1_warp', name='LFO 1 Cv1 Warp', address='/radiator/lfo1/cv1/warp', value_type='float', direction='RX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', notes='CV1 → warp depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo2_cv1_warp', name='LFO 2 Cv1 Warp', address='/radiator/lfo2/cv1/warp', value_type='float', direction='RX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', notes='CV1 → warp depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo3_cv1_warp', name='LFO 3 Cv1 Warp', address='/radiator/lfo3/cv1/warp', value_type='float', direction='RX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', notes='CV1 → warp depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo1_cv1_speed', name='LFO 1 Cv1 Speed', address='/radiator/lfo1/cv1/speed', value_type='float', direction='RX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', notes='CV1 → speed depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo2_cv1_speed', name='LFO 2 Cv1 Speed', address='/radiator/lfo2/cv1/speed', value_type='float', direction='RX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', notes='CV1 → speed depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo3_cv1_speed', name='LFO 3 Cv1 Speed', address='/radiator/lfo3/cv1/speed', value_type='float', direction='RX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', notes='CV1 → speed depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo1_cv1_level', name='LFO 1 Cv1 Level', address='/radiator/lfo1/cv1/level', value_type='float', direction='RX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', notes='CV1 → level depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo2_cv1_level', name='LFO 2 Cv1 Level', address='/radiator/lfo2/cv1/level', value_type='float', direction='RX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', notes='CV1 → level depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo3_cv1_level', name='LFO 3 Cv1 Level', address='/radiator/lfo3/cv1/level', value_type='float', direction='RX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', notes='CV1 → level depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo1_cv4_warp', name='LFO 1 Cv4 Warp', address='/radiator/lfo1/cv4/warp', value_type='float', direction='RX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', notes='CV4 → warp depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo2_cv4_warp', name='LFO 2 Cv4 Warp', address='/radiator/lfo2/cv4/warp', value_type='float', direction='RX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', notes='CV4 → warp depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo3_cv4_warp', name='LFO 3 Cv4 Warp', address='/radiator/lfo3/cv4/warp', value_type='float', direction='RX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', notes='CV4 → warp depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo1_cv4_speed', name='LFO 1 Cv4 Speed', address='/radiator/lfo1/cv4/speed', value_type='float', direction='RX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', notes='CV4 → speed depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo2_cv4_speed', name='LFO 2 Cv4 Speed', address='/radiator/lfo2/cv4/speed', value_type='float', direction='RX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', notes='CV4 → speed depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo3_cv4_speed', name='LFO 3 Cv4 Speed', address='/radiator/lfo3/cv4/speed', value_type='float', direction='RX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', notes='CV4 → speed depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo1_cv4_level', name='LFO 1 Cv4 Level', address='/radiator/lfo1/cv4/level', value_type='float', direction='RX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', notes='CV4 → level depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo2_cv4_level', name='LFO 2 Cv4 Level', address='/radiator/lfo2/cv4/level', value_type='float', direction='RX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', notes='CV4 → level depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo3_cv4_level', name='LFO 3 Cv4 Level', address='/radiator/lfo3/cv4/level', value_type='float', direction='RX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', notes='CV4 → level depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo1_fft_band', name='LFO 1 Fft Band', address='/radiator/lfo1/fft_band', value_type='int', direction='RX+TX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', notes='FFT band index', native_min_value=0.0, native_max_value=255, native_step=1, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo2_fft_band', name='LFO 2 Fft Band', address='/radiator/lfo2/fft_band', value_type='int', direction='RX+TX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', notes='FFT band index', native_min_value=0.0, native_max_value=255, native_step=1, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo3_fft_band', name='LFO 3 Fft Band', address='/radiator/lfo3/fft_band', value_type='int', direction='RX+TX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', notes='FFT band index', native_min_value=0.0, native_max_value=255, native_step=1, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo1_fft_warp', name='LFO 1 Fft Warp', address='/radiator/lfo1/fft_warp', value_type='float', direction='RX+TX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', notes='FFT → warp depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo2_fft_warp', name='LFO 2 Fft Warp', address='/radiator/lfo2/fft_warp', value_type='float', direction='RX+TX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', notes='FFT → warp depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo3_fft_warp', name='LFO 3 Fft Warp', address='/radiator/lfo3/fft_warp', value_type='float', direction='RX+TX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', notes='FFT → warp depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo1_fft_speed', name='LFO 1 Fft Speed', address='/radiator/lfo1/fft_speed', value_type='float', direction='RX+TX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', notes='FFT → speed depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo2_fft_speed', name='LFO 2 Fft Speed', address='/radiator/lfo2/fft_speed', value_type='float', direction='RX+TX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', notes='FFT → speed depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo3_fft_speed', name='LFO 3 Fft Speed', address='/radiator/lfo3/fft_speed', value_type='float', direction='RX+TX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', notes='FFT → speed depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo1_fft_level', name='LFO 1 Fft Level', address='/radiator/lfo1/fft_level', value_type='float', direction='RX+TX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', notes='FFT → level depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo2_fft_level', name='LFO 2 Fft Level', address='/radiator/lfo2/fft_level', value_type='float', direction='RX+TX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', notes='FFT → level depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo3_fft_level', name='LFO 3 Fft Level', address='/radiator/lfo3/fft_level', value_type='float', direction='RX+TX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', notes='FFT → level depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo1_lfo2_warp', name='LFO 1 LFO 2 Warp', address='/radiator/lfo1/lfo2/warp', value_type='float', direction='RX+TX', section='LFO × LFO MODULATION  (e.g. lfo1/lfo2, lfo1/lfo3, lfo2/lfo1 …)', notes='LFO-B → LFO-A warp depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo1_lfo3_warp', name='LFO 1 LFO 3 Warp', address='/radiator/lfo1/lfo3/warp', value_type='float', direction='RX+TX', section='LFO × LFO MODULATION  (e.g. lfo1/lfo2, lfo1/lfo3, lfo2/lfo1 …)', notes='LFO-B → LFO-A warp depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo2_lfo1_warp', name='LFO 2 LFO 1 Warp', address='/radiator/lfo2/lfo1/warp', value_type='float', direction='RX+TX', section='LFO × LFO MODULATION  (e.g. lfo1/lfo2, lfo1/lfo3, lfo2/lfo1 …)', notes='LFO-B → LFO-A warp depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo2_lfo3_warp', name='LFO 2 LFO 3 Warp', address='/radiator/lfo2/lfo3/warp', value_type='float', direction='RX+TX', section='LFO × LFO MODULATION  (e.g. lfo1/lfo2, lfo1/lfo3, lfo2/lfo1 …)', notes='LFO-B → LFO-A warp depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo3_lfo1_warp', name='LFO 3 LFO 1 Warp', address='/radiator/lfo3/lfo1/warp', value_type='float', direction='RX+TX', section='LFO × LFO MODULATION  (e.g. lfo1/lfo2, lfo1/lfo3, lfo2/lfo1 …)', notes='LFO-B → LFO-A warp depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo3_lfo2_warp', name='LFO 3 LFO 2 Warp', address='/radiator/lfo3/lfo2/warp', value_type='float', direction='RX+TX', section='LFO × LFO MODULATION  (e.g. lfo1/lfo2, lfo1/lfo3, lfo2/lfo1 …)', notes='LFO-B → LFO-A warp depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo1_lfo2_speed', name='LFO 1 LFO 2 Speed', address='/radiator/lfo1/lfo2/speed', value_type='float', direction='RX+TX', section='LFO × LFO MODULATION  (e.g. lfo1/lfo2, lfo1/lfo3, lfo2/lfo1 …)', notes='LFO-B → LFO-A speed depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo1_lfo3_speed', name='LFO 1 LFO 3 Speed', address='/radiator/lfo1/lfo3/speed', value_type='float', direction='RX+TX', section='LFO × LFO MODULATION  (e.g. lfo1/lfo2, lfo1/lfo3, lfo2/lfo1 …)', notes='LFO-B → LFO-A speed depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo2_lfo1_speed', name='LFO 2 LFO 1 Speed', address='/radiator/lfo2/lfo1/speed', value_type='float', direction='RX+TX', section='LFO × LFO MODULATION  (e.g. lfo1/lfo2, lfo1/lfo3, lfo2/lfo1 …)', notes='LFO-B → LFO-A speed depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo2_lfo3_speed', name='LFO 2 LFO 3 Speed', address='/radiator/lfo2/lfo3/speed', value_type='float', direction='RX+TX', section='LFO × LFO MODULATION  (e.g. lfo1/lfo2, lfo1/lfo3, lfo2/lfo1 …)', notes='LFO-B → LFO-A speed depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo3_lfo1_speed', name='LFO 3 LFO 1 Speed', address='/radiator/lfo3/lfo1/speed', value_type='float', direction='RX+TX', section='LFO × LFO MODULATION  (e.g. lfo1/lfo2, lfo1/lfo3, lfo2/lfo1 …)', notes='LFO-B → LFO-A speed depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo3_lfo2_speed', name='LFO 3 LFO 2 Speed', address='/radiator/lfo3/lfo2/speed', value_type='float', direction='RX+TX', section='LFO × LFO MODULATION  (e.g. lfo1/lfo2, lfo1/lfo3, lfo2/lfo1 …)', notes='LFO-B → LFO-A speed depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo1_lfo2_level', name='LFO 1 LFO 2 Level', address='/radiator/lfo1/lfo2/level', value_type='float', direction='RX+TX', section='LFO × LFO MODULATION  (e.g. lfo1/lfo2, lfo1/lfo3, lfo2/lfo1 …)', notes='LFO-B → LFO-A level depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo1_lfo3_level', name='LFO 1 LFO 3 Level', address='/radiator/lfo1/lfo3/level', value_type='float', direction='RX+TX', section='LFO × LFO MODULATION  (e.g. lfo1/lfo2, lfo1/lfo3, lfo2/lfo1 …)', notes='LFO-B → LFO-A level depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo2_lfo1_level', name='LFO 2 LFO 1 Level', address='/radiator/lfo2/lfo1/level', value_type='float', direction='RX+TX', section='LFO × LFO MODULATION  (e.g. lfo1/lfo2, lfo1/lfo3, lfo2/lfo1 …)', notes='LFO-B → LFO-A level depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo2_lfo3_level', name='LFO 2 LFO 3 Level', address='/radiator/lfo2/lfo3/level', value_type='float', direction='RX+TX', section='LFO × LFO MODULATION  (e.g. lfo1/lfo2, lfo1/lfo3, lfo2/lfo1 …)', notes='LFO-B → LFO-A level depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo3_lfo1_level', name='LFO 3 LFO 1 Level', address='/radiator/lfo3/lfo1/level', value_type='float', direction='RX+TX', section='LFO × LFO MODULATION  (e.g. lfo1/lfo2, lfo1/lfo3, lfo2/lfo1 …)', notes='LFO-B → LFO-A level depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo3_lfo2_level', name='LFO 3 LFO 2 Level', address='/radiator/lfo3/lfo2/level', value_type='float', direction='RX+TX', section='LFO × LFO MODULATION  (e.g. lfo1/lfo2, lfo1/lfo3, lfo2/lfo1 …)', notes='LFO-B → LFO-A level depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_shapeA_warp', name='Shape A Warp', address='/radiator/shapeA/warp', value_type='float', direction='RX+TX', section='SHAPE A', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=True),
    RadiatorOscDescription(key='radiator_shapeA_warp_type', name='Shape A Warp Type', address='/radiator/shapeA/warp_type', value_type='int', direction='RX+TX', section='SHAPE A', notes='Warp type index', native_min_value=0.0, native_max_value=255, native_step=1, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_shapeA_shape', name='Shape A Shape', address='/radiator/shapeA/shape', value_type='int', direction='RX+TX', section='SHAPE A', notes='Shape file index', native_min_value=0.0, native_max_value=255, native_step=1, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_shapeA_autorotate_speed', name='Shape A Autorotate Speed', address='/radiator/shapeA/autorotate_speed', value_type='float', direction='RX+TX', section='SHAPE A', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_shapeA_manual_rotate', name='Shape A Manual Rotate', address='/radiator/shapeA/manual_rotate', value_type='float', direction='RX+TX', section='SHAPE A', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_shapeA_rotate_axis', name='Shape A Rotate Axis', address='/radiator/shapeA/rotate_axis', value_type='int', direction='RX+TX', section='SHAPE A', notes='0=Z  1=X  2=Y', native_min_value=0.0, native_max_value=1.0, native_step=1, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_shapeA_size', name='Shape A Size', address='/radiator/shapeA/size', value_type='float', direction='RX+TX', section='SHAPE A', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=True),
    RadiatorOscDescription(key='radiator_shapeA_speed', name='Shape A Speed', address='/radiator/shapeA/speed', value_type='float', direction='RX+TX', section='SHAPE A', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=True),
    RadiatorOscDescription(key='radiator_shapeA_lfo1_warp', name='Shape A LFO 1 Warp', address='/radiator/shapeA/lfo1/warp', value_type='float', direction='RX+TX', section='SHAPE A – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → warp depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_shapeA_lfo2_warp', name='Shape A LFO 2 Warp', address='/radiator/shapeA/lfo2/warp', value_type='float', direction='RX+TX', section='SHAPE A – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → warp depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_shapeA_lfo3_warp', name='Shape A LFO 3 Warp', address='/radiator/shapeA/lfo3/warp', value_type='float', direction='RX+TX', section='SHAPE A – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → warp depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_shapeA_lfo1_rotate', name='Shape A LFO 1 Rotate', address='/radiator/shapeA/lfo1/rotate', value_type='float', direction='RX+TX', section='SHAPE A – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → rotate depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_shapeA_lfo2_rotate', name='Shape A LFO 2 Rotate', address='/radiator/shapeA/lfo2/rotate', value_type='float', direction='RX+TX', section='SHAPE A – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → rotate depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_shapeA_lfo3_rotate', name='Shape A LFO 3 Rotate', address='/radiator/shapeA/lfo3/rotate', value_type='float', direction='RX+TX', section='SHAPE A – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → rotate depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_shapeA_lfo1_size', name='Shape A LFO 1 Size', address='/radiator/shapeA/lfo1/size', value_type='float', direction='RX+TX', section='SHAPE A – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → size depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_shapeA_lfo2_size', name='Shape A LFO 2 Size', address='/radiator/shapeA/lfo2/size', value_type='float', direction='RX+TX', section='SHAPE A – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → size depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_shapeA_lfo3_size', name='Shape A LFO 3 Size', address='/radiator/shapeA/lfo3/size', value_type='float', direction='RX+TX', section='SHAPE A – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → size depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_shapeA_lfo1_speed', name='Shape A LFO 1 Speed', address='/radiator/shapeA/lfo1/speed', value_type='float', direction='RX+TX', section='SHAPE A – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → speed depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_shapeA_lfo2_speed', name='Shape A LFO 2 Speed', address='/radiator/shapeA/lfo2/speed', value_type='float', direction='RX+TX', section='SHAPE A – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → speed depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_shapeA_lfo3_speed', name='Shape A LFO 3 Speed', address='/radiator/shapeA/lfo3/speed', value_type='float', direction='RX+TX', section='SHAPE A – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → speed depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_shapeB_warp', name='Shape B Warp', address='/radiator/shapeB/warp', value_type='float', direction='RX+TX', section='SHAPE B', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=True),
    RadiatorOscDescription(key='radiator_shapeB_warp_type', name='Shape B Warp Type', address='/radiator/shapeB/warp_type', value_type='int', direction='RX+TX', section='SHAPE B', notes='Warp type index', native_min_value=0.0, native_max_value=255, native_step=1, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_shapeB_shape', name='Shape B Shape', address='/radiator/shapeB/shape', value_type='int', direction='RX+TX', section='SHAPE B', notes='Shape file index', native_min_value=0.0, native_max_value=255, native_step=1, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_shapeB_autorotate_speed', name='Shape B Autorotate Speed', address='/radiator/shapeB/autorotate_speed', value_type='float', direction='RX+TX', section='SHAPE B', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_shapeB_manual_rotate', name='Shape B Manual Rotate', address='/radiator/shapeB/manual_rotate', value_type='float', direction='RX+TX', section='SHAPE B', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_shapeB_rotate_axis', name='Shape B Rotate Axis', address='/radiator/shapeB/rotate_axis', value_type='int', direction='RX+TX', section='SHAPE B', notes='0=Z  1=X  2=Y', native_min_value=0.0, native_max_value=1.0, native_step=1, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_shapeB_size', name='Shape B Size', address='/radiator/shapeB/size', value_type='float', direction='RX+TX', section='SHAPE B', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=True),
    RadiatorOscDescription(key='radiator_shapeB_speed', name='Shape B Speed', address='/radiator/shapeB/speed', value_type='float', direction='RX+TX', section='SHAPE B', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=True),
    RadiatorOscDescription(key='radiator_shapeB_lfo1_warp', name='Shape B LFO 1 Warp', address='/radiator/shapeB/lfo1/warp', value_type='float', direction='RX+TX', section='SHAPE B – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → warp depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_shapeB_lfo2_warp', name='Shape B LFO 2 Warp', address='/radiator/shapeB/lfo2/warp', value_type='float', direction='RX+TX', section='SHAPE B – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → warp depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_shapeB_lfo3_warp', name='Shape B LFO 3 Warp', address='/radiator/shapeB/lfo3/warp', value_type='float', direction='RX+TX', section='SHAPE B – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → warp depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_shapeB_lfo1_rotate', name='Shape B LFO 1 Rotate', address='/radiator/shapeB/lfo1/rotate', value_type='float', direction='RX+TX', section='SHAPE B – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → rotate depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_shapeB_lfo2_rotate', name='Shape B LFO 2 Rotate', address='/radiator/shapeB/lfo2/rotate', value_type='float', direction='RX+TX', section='SHAPE B – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → rotate depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_shapeB_lfo3_rotate', name='Shape B LFO 3 Rotate', address='/radiator/shapeB/lfo3/rotate', value_type='float', direction='RX+TX', section='SHAPE B – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → rotate depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_shapeB_lfo1_size', name='Shape B LFO 1 Size', address='/radiator/shapeB/lfo1/size', value_type='float', direction='RX+TX', section='SHAPE B – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → size depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_shapeB_lfo2_size', name='Shape B LFO 2 Size', address='/radiator/shapeB/lfo2/size', value_type='float', direction='RX+TX', section='SHAPE B – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → size depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_shapeB_lfo3_size', name='Shape B LFO 3 Size', address='/radiator/shapeB/lfo3/size', value_type='float', direction='RX+TX', section='SHAPE B – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → size depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_shapeB_lfo1_speed', name='Shape B LFO 1 Speed', address='/radiator/shapeB/lfo1/speed', value_type='float', direction='RX+TX', section='SHAPE B – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → speed depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_shapeB_lfo2_speed', name='Shape B LFO 2 Speed', address='/radiator/shapeB/lfo2/speed', value_type='float', direction='RX+TX', section='SHAPE B – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → speed depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_shapeB_lfo3_speed', name='Shape B LFO 3 Speed', address='/radiator/shapeB/lfo3/speed', value_type='float', direction='RX+TX', section='SHAPE B – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → speed depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_trans_warp', name='Trans Warp', address='/radiator/trans/warp', value_type='float', direction='RX+TX', section='TRANSFORMER', notes='Also = XY Scope displacement scale', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_trans_rotate_offset', name='Trans Rotate Offset', address='/radiator/trans/rotate_offset', value_type='float', direction='RX+TX', section='TRANSFORMER', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_trans_type', name='Trans Type', address='/radiator/trans/type', value_type='int', direction='RX+TX', section='TRANSFORMER', notes='Trans type index', native_min_value=0.0, native_max_value=255, native_step=1, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_trans_source', name='Trans Source', address='/radiator/trans/source', value_type='int', direction='RX+TX', section='TRANSFORMER', notes='Source index: ShA+B / ShA / ShB / None', native_min_value=0.0, native_max_value=255, native_step=1, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_trans_axis_tilt', name='Trans Axis Tilt', address='/radiator/trans/axis_tilt', value_type='float', direction='RX+TX', section='TRANSFORMER', notes='Bidirectional', native_min_value=-1.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_trans_rotate', name='Trans Rotate', address='/radiator/trans/rotate', value_type='float', direction='RX+TX', section='TRANSFORMER', notes='Rotation oscillator freq, bidirectional', native_min_value=-1.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_trans_size', name='Trans Size', address='/radiator/trans/size', value_type='float', direction='RX+TX', section='TRANSFORMER', notes='→ master_proc_ext_size; min 0.01', native_min_value=0.01, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_trans_lfo1_warp', name='Trans LFO 1 Warp', address='/radiator/trans/lfo1/warp', value_type='float', direction='RX+TX', section='TRANSFORMER – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → warp depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_trans_lfo2_warp', name='Trans LFO 2 Warp', address='/radiator/trans/lfo2/warp', value_type='float', direction='RX+TX', section='TRANSFORMER – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → warp depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_trans_lfo3_warp', name='Trans LFO 3 Warp', address='/radiator/trans/lfo3/warp', value_type='float', direction='RX+TX', section='TRANSFORMER – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → warp depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_trans_lfo1_rotate_offset', name='Trans LFO 1 Rotate Offset', address='/radiator/trans/lfo1/rotate_offset', value_type='float', direction='RX+TX', section='TRANSFORMER – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → rotate offset depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_trans_lfo2_rotate_offset', name='Trans LFO 2 Rotate Offset', address='/radiator/trans/lfo2/rotate_offset', value_type='float', direction='RX+TX', section='TRANSFORMER – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → rotate offset depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_trans_lfo3_rotate_offset', name='Trans LFO 3 Rotate Offset', address='/radiator/trans/lfo3/rotate_offset', value_type='float', direction='RX+TX', section='TRANSFORMER – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → rotate offset depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_trans_lfo1_axis_tilt', name='Trans LFO 1 Axis Tilt', address='/radiator/trans/lfo1/axis_tilt', value_type='float', direction='RX+TX', section='TRANSFORMER – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → axis tilt depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_trans_lfo2_axis_tilt', name='Trans LFO 2 Axis Tilt', address='/radiator/trans/lfo2/axis_tilt', value_type='float', direction='RX+TX', section='TRANSFORMER – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → axis tilt depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_trans_lfo3_axis_tilt', name='Trans LFO 3 Axis Tilt', address='/radiator/trans/lfo3/axis_tilt', value_type='float', direction='RX+TX', section='TRANSFORMER – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → axis tilt depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_trans_lfo1_rotation', name='Trans LFO 1 Rotation', address='/radiator/trans/lfo1/rotation', value_type='float', direction='RX+TX', section='TRANSFORMER – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → rotation depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_trans_lfo2_rotation', name='Trans LFO 2 Rotation', address='/radiator/trans/lfo2/rotation', value_type='float', direction='RX+TX', section='TRANSFORMER – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → rotation depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_trans_lfo3_rotation', name='Trans LFO 3 Rotation', address='/radiator/trans/lfo3/rotation', value_type='float', direction='RX+TX', section='TRANSFORMER – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → rotation depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_trans_lfo1_size', name='Trans LFO 1 Size', address='/radiator/trans/lfo1/size', value_type='float', direction='RX+TX', section='TRANSFORMER – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → local geometry size depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_trans_lfo2_size', name='Trans LFO 2 Size', address='/radiator/trans/lfo2/size', value_type='float', direction='RX+TX', section='TRANSFORMER – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → local geometry size depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_trans_lfo3_size', name='Trans LFO 3 Size', address='/radiator/trans/lfo3/size', value_type='float', direction='RX+TX', section='TRANSFORMER – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → local geometry size depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_trans_lfo1_pos_x', name='Trans LFO 1 Pos X', address='/radiator/trans/lfo1/pos_x', value_type='float', direction='RX+TX', section='TRANSFORMER – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → XY Scope X displacement depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_trans_lfo2_pos_x', name='Trans LFO 2 Pos X', address='/radiator/trans/lfo2/pos_x', value_type='float', direction='RX+TX', section='TRANSFORMER – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → XY Scope X displacement depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_trans_lfo3_pos_x', name='Trans LFO 3 Pos X', address='/radiator/trans/lfo3/pos_x', value_type='float', direction='RX+TX', section='TRANSFORMER – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → XY Scope X displacement depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_trans_lfo1_pos_y', name='Trans LFO 1 Pos Y', address='/radiator/trans/lfo1/pos_y', value_type='float', direction='RX+TX', section='TRANSFORMER – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → XY Scope Y displacement depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_trans_lfo2_pos_y', name='Trans LFO 2 Pos Y', address='/radiator/trans/lfo2/pos_y', value_type='float', direction='RX+TX', section='TRANSFORMER – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → XY Scope Y displacement depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_trans_lfo3_pos_y', name='Trans LFO 3 Pos Y', address='/radiator/trans/lfo3/pos_y', value_type='float', direction='RX+TX', section='TRANSFORMER – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → XY Scope Y displacement depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_trans_lfo1_pos_z', name='Trans LFO 1 Pos Z', address='/radiator/trans/lfo1/pos_z', value_type='float', direction='RX+TX', section='TRANSFORMER – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → XY Scope Z displacement depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_trans_lfo2_pos_z', name='Trans LFO 2 Pos Z', address='/radiator/trans/lfo2/pos_z', value_type='float', direction='RX+TX', section='TRANSFORMER – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → XY Scope Z displacement depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_trans_lfo3_pos_z', name='Trans LFO 3 Pos Z', address='/radiator/trans/lfo3/pos_z', value_type='float', direction='RX+TX', section='TRANSFORMER – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → XY Scope Z displacement depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_clone_spread', name='Clone Spread', address='/radiator/clone/spread', value_type='float', direction='RX+TX', section='CLONE', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_clone_rotate_offset', name='Clone Rotate Offset', address='/radiator/clone/rotate_offset', value_type='float', direction='RX+TX', section='CLONE', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_clone_type', name='Clone Type', address='/radiator/clone/type', value_type='int', direction='RX+TX', section='CLONE', notes='Clone type index', native_min_value=0.0, native_max_value=255, native_step=1, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_clone_source', name='Clone Source', address='/radiator/clone/source', value_type='int', direction='RX+TX', section='CLONE', notes='Clone source index', native_min_value=0.0, native_max_value=255, native_step=1, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_clone_speed', name='Clone Speed', address='/radiator/clone/speed', value_type='float', direction='RX+TX', section='CLONE', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_clone_rotation_x', name='Clone Rotation X', address='/radiator/clone/rotation_x', value_type='float', direction='RX+TX', section='CLONE', notes='3D rotation around X axis', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_clone_rotation_z', name='Clone Rotation Z', address='/radiator/clone/rotation_z', value_type='float', direction='RX+TX', section='CLONE', notes='3D rotation around Z axis', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_clone_lfo1_spread', name='Clone LFO 1 Spread', address='/radiator/clone/lfo1/spread', value_type='float', direction='RX+TX', section='CLONE – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → spread depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_clone_lfo2_spread', name='Clone LFO 2 Spread', address='/radiator/clone/lfo2/spread', value_type='float', direction='RX+TX', section='CLONE – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → spread depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_clone_lfo3_spread', name='Clone LFO 3 Spread', address='/radiator/clone/lfo3/spread', value_type='float', direction='RX+TX', section='CLONE – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → spread depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_clone_lfo1_rotate_offset', name='Clone LFO 1 Rotate Offset', address='/radiator/clone/lfo1/rotate_offset', value_type='float', direction='RX+TX', section='CLONE – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → rotate offset depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_clone_lfo2_rotate_offset', name='Clone LFO 2 Rotate Offset', address='/radiator/clone/lfo2/rotate_offset', value_type='float', direction='RX+TX', section='CLONE – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → rotate offset depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_clone_lfo3_rotate_offset', name='Clone LFO 3 Rotate Offset', address='/radiator/clone/lfo3/rotate_offset', value_type='float', direction='RX+TX', section='CLONE – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → rotate offset depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_clone_lfo1_speed', name='Clone LFO 1 Speed', address='/radiator/clone/lfo1/speed', value_type='float', direction='RX+TX', section='CLONE – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → speed depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_clone_lfo2_speed', name='Clone LFO 2 Speed', address='/radiator/clone/lfo2/speed', value_type='float', direction='RX+TX', section='CLONE – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → speed depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_clone_lfo3_speed', name='Clone LFO 3 Speed', address='/radiator/clone/lfo3/speed', value_type='float', direction='RX+TX', section='CLONE – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → speed depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_clone_lfo1_rotation_x', name='Clone LFO 1 Rotation X', address='/radiator/clone/lfo1/rotation_x', value_type='float', direction='RX+TX', section='CLONE – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → X rotation depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_clone_lfo2_rotation_x', name='Clone LFO 2 Rotation X', address='/radiator/clone/lfo2/rotation_x', value_type='float', direction='RX+TX', section='CLONE – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → X rotation depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_clone_lfo3_rotation_x', name='Clone LFO 3 Rotation X', address='/radiator/clone/lfo3/rotation_x', value_type='float', direction='RX+TX', section='CLONE – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → X rotation depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_clone_lfo1_rotation_z', name='Clone LFO 1 Rotation Z', address='/radiator/clone/lfo1/rotation_z', value_type='float', direction='RX+TX', section='CLONE – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → Z rotation depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_clone_lfo2_rotation_z', name='Clone LFO 2 Rotation Z', address='/radiator/clone/lfo2/rotation_z', value_type='float', direction='RX+TX', section='CLONE – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → Z rotation depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_clone_lfo3_rotation_z', name='Clone LFO 3 Rotation Z', address='/radiator/clone/lfo3/rotation_z', value_type='float', direction='RX+TX', section='CLONE – LFO ROUTING  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO → Z rotation depth', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_master_size', name='Master Size', address='/radiator/master/size', value_type='float', direction='RX+TX', section='MASTER', notes='Physical pot value (read-only from panel)', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_master_level', name='Master Level', address='/radiator/master/level', value_type='float', direction='RX+TX', section='MASTER', notes='Physical pot value (read-only from panel)', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_master_x_scale', name='Master X Scale', address='/radiator/master/x_scale', value_type='float', direction='RX+TX', section='MASTER', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_master_y_scale', name='Master Y Scale', address='/radiator/master/y_scale', value_type='float', direction='RX+TX', section='MASTER', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_master_x_offset', name='Master X Offset', address='/radiator/master/x_offset', value_type='float', direction='RX+TX', section='MASTER', notes='Bidirectional', native_min_value=-1.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_master_y_offset', name='Master Y Offset', address='/radiator/master/y_offset', value_type='float', direction='RX+TX', section='MASTER', notes='Bidirectional', native_min_value=-1.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_master_r_level', name='Master R Level', address='/radiator/master/r_level', value_type='float', direction='RX+TX', section='MASTER', notes='Red channel level', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_master_g_level', name='Master G Level', address='/radiator/master/g_level', value_type='float', direction='RX+TX', section='MASTER', notes='Green channel level', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_master_b_level', name='Master B Level', address='/radiator/master/b_level', value_type='float', direction='RX+TX', section='MASTER', notes='Blue channel level', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_master_r_bias', name='Master R Bias', address='/radiator/master/r_bias', value_type='float', direction='RX+TX', section='MASTER', notes='Red channel bias', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_master_g_bias', name='Master G Bias', address='/radiator/master/g_bias', value_type='float', direction='RX+TX', section='MASTER', notes='Green channel bias', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_master_b_bias', name='Master B Bias', address='/radiator/master/b_bias', value_type='float', direction='RX+TX', section='MASTER', notes='Blue channel bias', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_master_filter', name='Master Filter', address='/radiator/master/filter', value_type='int', direction='RX+TX', section='MASTER', notes='Master filter type index', native_min_value=0.0, native_max_value=255, native_step=1, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_master_geocorr_x_keystone', name='Master Geometric Correction X Keystone', address='/radiator/master/geocorr/x_keystone', value_type='float', direction='RX+TX', section='MASTER – GEOMETRIC CORRECTION', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_master_geocorr_y_keystone', name='Master Geometric Correction Y Keystone', address='/radiator/master/geocorr/y_keystone', value_type='float', direction='RX+TX', section='MASTER – GEOMETRIC CORRECTION', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_master_geocorr_x_bow', name='Master Geometric Correction X Bow', address='/radiator/master/geocorr/x_bow', value_type='float', direction='RX+TX', section='MASTER – GEOMETRIC CORRECTION', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_master_geocorr_y_bow', name='Master Geometric Correction Y Bow', address='/radiator/master/geocorr/y_bow', value_type='float', direction='RX+TX', section='MASTER – GEOMETRIC CORRECTION', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_master_geocorr_x_pincushion', name='Master Geometric Correction X Pincushion', address='/radiator/master/geocorr/x_pincushion', value_type='float', direction='RX+TX', section='MASTER – GEOMETRIC CORRECTION', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_master_geocorr_y_pincushion', name='Master Geometric Correction Y Pincushion', address='/radiator/master/geocorr/y_pincushion', value_type='float', direction='RX+TX', section='MASTER – GEOMETRIC CORRECTION', native_min_value=0.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_master_corner_tl_x', name='Master Corner Tl X', address='/radiator/master/corner/tl_x', value_type='float', direction='RX+TX', section='MASTER – CORNER MESH', notes='Top-left X', native_min_value=-1.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_master_corner_tl_y', name='Master Corner Tl Y', address='/radiator/master/corner/tl_y', value_type='float', direction='RX+TX', section='MASTER – CORNER MESH', notes='Top-left Y', native_min_value=-1.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_master_corner_tr_x', name='Master Corner Tr X', address='/radiator/master/corner/tr_x', value_type='float', direction='RX+TX', section='MASTER – CORNER MESH', notes='Top-right X', native_min_value=-1.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_master_corner_tr_y', name='Master Corner Tr Y', address='/radiator/master/corner/tr_y', value_type='float', direction='RX+TX', section='MASTER – CORNER MESH', notes='Top-right Y', native_min_value=-1.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_master_corner_bl_x', name='Master Corner Bl X', address='/radiator/master/corner/bl_x', value_type='float', direction='RX+TX', section='MASTER – CORNER MESH', notes='Bottom-left X', native_min_value=-1.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_master_corner_bl_y', name='Master Corner Bl Y', address='/radiator/master/corner/bl_y', value_type='float', direction='RX+TX', section='MASTER – CORNER MESH', notes='Bottom-left Y', native_min_value=-1.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_master_corner_br_x', name='Master Corner Br X', address='/radiator/master/corner/br_x', value_type='float', direction='RX+TX', section='MASTER – CORNER MESH', notes='Bottom-right X', native_min_value=-1.0, native_max_value=1.0, native_step=0.01, entity_registry_enabled_default=False),
)
SWITCH_DESCRIPTIONS: Final[tuple[RadiatorOscDescription, ...]] = (
    RadiatorOscDescription(key='radiator_color_mod_on', name='Color Mod On', address='/radiator/color/mod/on', value_type='bool', direction='RX+TX', section='COLOR', entity_registry_enabled_default=True),
    RadiatorOscDescription(key='radiator_color_rgb_mode', name='Color Rgb Mode', address='/radiator/color/rgb_mode', value_type='bool', direction='RX', section='COLOR', entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_color_spectral', name='Color Spectral', address='/radiator/color/spectral', value_type='bool', direction='RX+TX', section='COLOR', entity_registry_enabled_default=True),
    RadiatorOscDescription(key='radiator_lfo1_on', name='LFO 1 On', address='/radiator/lfo1/on', value_type='bool', direction='RX+TX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', entity_registry_enabled_default=True),
    RadiatorOscDescription(key='radiator_lfo2_on', name='LFO 2 On', address='/radiator/lfo2/on', value_type='bool', direction='RX+TX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', entity_registry_enabled_default=True),
    RadiatorOscDescription(key='radiator_lfo3_on', name='LFO 3 On', address='/radiator/lfo3/on', value_type='bool', direction='RX+TX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', entity_registry_enabled_default=True),
    RadiatorOscDescription(key='radiator_shapeA_invert', name='Shape A Invert', address='/radiator/shapeA/invert', value_type='bool', direction='RX+TX', section='SHAPE A', notes='Shape A only', entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_shapeA_autorotate', name='Shape A Autorotate', address='/radiator/shapeA/autorotate', value_type='bool', direction='RX+TX', section='SHAPE A', entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_shapeA_on', name='Shape A On', address='/radiator/shapeA/on', value_type='bool', direction='RX+TX', section='SHAPE A', entity_registry_enabled_default=True),
    RadiatorOscDescription(key='radiator_shapeB_sync', name='Shape B Sync', address='/radiator/shapeB/sync', value_type='bool', direction='RX+TX', section='SHAPE B', notes='Shape B only', entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_shapeB_autorotate', name='Shape B Autorotate', address='/radiator/shapeB/autorotate', value_type='bool', direction='RX+TX', section='SHAPE B', entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_shapeB_on', name='Shape B On', address='/radiator/shapeB/on', value_type='bool', direction='RX+TX', section='SHAPE B', entity_registry_enabled_default=True),
    RadiatorOscDescription(key='radiator_master_blackout', name='Blackout', address='/radiator/master/blackout', value_type='bool', direction='RX+TX', section='MASTER', entity_registry_enabled_default=True),
    RadiatorOscDescription(key='radiator_master_x_flip', name='Master X Flip', address='/radiator/master/x_flip', value_type='bool', direction='RX+TX', section='MASTER', entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_master_y_flip', name='Master Y Flip', address='/radiator/master/y_flip', value_type='bool', direction='RX+TX', section='MASTER', entity_registry_enabled_default=False),
)
SENSOR_DESCRIPTIONS: Final[tuple[RadiatorOscDescription, ...]] = (
    RadiatorOscDescription(key='radiator_preset_current', name='Preset Current', address='/radiator/preset/current', value_type='float', direction='TX', section='PRESET', notes='Current preset number (sent on dump)', entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_color_mod_type_name', name='Color Mod Type Name', address='/radiator/color/mod/type/name', value_type='string', direction='TX', section='COLOR', notes='Color mod type name string', entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_color_mode_name', name='Color Mode Name', address='/radiator/color/mode/name', value_type='string', direction='TX', section='COLOR', notes='HSV / RGB', entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_color_swatch', name='Color Swatch', address='/radiator/color/swatch', value_type='string', direction='TX', section='COLOR', notes='Current color swatch as hex', entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo1_warp_type_name', name='LFO 1 Warp Type Name', address='/radiator/lfo1/warp_type/name', value_type='string', direction='TX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', notes='Warp type name string', entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo2_warp_type_name', name='LFO 2 Warp Type Name', address='/radiator/lfo2/warp_type/name', value_type='string', direction='TX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', notes='Warp type name string', entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo3_warp_type_name', name='LFO 3 Warp Type Name', address='/radiator/lfo3/warp_type/name', value_type='string', direction='TX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', notes='Warp type name string', entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo1_shape_name', name='LFO 1 Shape Name', address='/radiator/lfo1/shape/name', value_type='string', direction='TX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO shape name string', entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo2_shape_name', name='LFO 2 Shape Name', address='/radiator/lfo2/shape/name', value_type='string', direction='TX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO shape name string', entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo3_shape_name', name='LFO 3 Shape Name', address='/radiator/lfo3/shape/name', value_type='string', direction='TX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', notes='LFO shape name string', entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo1_fft_band_name', name='LFO 1 Fft Band Name', address='/radiator/lfo1/fft_band/name', value_type='string', direction='TX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', notes='FFT band name string', entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo2_fft_band_name', name='LFO 2 Fft Band Name', address='/radiator/lfo2/fft_band/name', value_type='string', direction='TX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', notes='FFT band name string', entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_lfo3_fft_band_name', name='LFO 3 Fft Band Name', address='/radiator/lfo3/fft_band/name', value_type='string', direction='TX', section='LFO  (repeat for lfo1 / lfo2 / lfo3)', notes='FFT band name string', entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_shapeA_warp_type_name', name='Shape A Warp Type Name', address='/radiator/shapeA/warp_type/name', value_type='string', direction='TX', section='SHAPE A', notes='Warp type name string', entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_shapeA_shape_name', name='Shape A Shape Name', address='/radiator/shapeA/shape/name', value_type='string', direction='TX', section='SHAPE A', notes='Shape name string', entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_shapeA_rotate_axis_name', name='Shape A Rotate Axis Name', address='/radiator/shapeA/rotate_axis/name', value_type='string', direction='TX', section='SHAPE A', notes='Z / X / Y', entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_shapeB_warp_type_name', name='Shape B Warp Type Name', address='/radiator/shapeB/warp_type/name', value_type='string', direction='TX', section='SHAPE B', notes='Warp type name string', entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_shapeB_shape_name', name='Shape B Shape Name', address='/radiator/shapeB/shape/name', value_type='string', direction='TX', section='SHAPE B', notes='Shape name string', entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_shapeB_rotate_axis_name', name='Shape B Rotate Axis Name', address='/radiator/shapeB/rotate_axis/name', value_type='string', direction='TX', section='SHAPE B', notes='Z / X / Y', entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_trans_type_name', name='Trans Type Name', address='/radiator/trans/type/name', value_type='string', direction='TX', section='TRANSFORMER', notes='Trans type name string', entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_trans_source_name', name='Trans Source Name', address='/radiator/trans/source/name', value_type='string', direction='TX', section='TRANSFORMER', notes='Source name string', entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_clone_type_name', name='Clone Type Name', address='/radiator/clone/type/name', value_type='string', direction='TX', section='CLONE', notes='Clone type name string', entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_clone_source_name', name='Clone Source Name', address='/radiator/clone/source/name', value_type='string', direction='TX', section='CLONE', notes='Clone source name string', entity_registry_enabled_default=False),
    RadiatorOscDescription(key='radiator_master_filter_name', name='Master Filter Name', address='/radiator/master/filter/name', value_type='string', direction='TX', section='MASTER', notes='Master filter name string', entity_registry_enabled_default=False),
)
ALL_KNOWN_ADDRESSES: Final[set[str]] = {
    '/radiator/preset',
    '/radiator/preset/current',
    '/radiator/color/hue',
    '/radiator/color/saturate',
    '/radiator/color/value',
    '/radiator/color/mod/p1',
    '/radiator/color/mod/p2',
    '/radiator/color/mod/p3',
    '/radiator/color/mod/type',
    '/radiator/color/mod/type/name',
    '/radiator/color/mod/on',
    '/radiator/color/mode',
    '/radiator/color/mode/name',
    '/radiator/color/rgb_mode',
    '/radiator/color/spectral',
    '/radiator/color/z_depth',
    '/radiator/color/custom_hue/0',
    '/radiator/color/custom_hue/1',
    '/radiator/color/custom_hue/2',
    '/radiator/color/swatch',
    '/radiator/color/lfo1/h_level',
    '/radiator/color/lfo2/h_level',
    '/radiator/color/lfo3/h_level',
    '/radiator/color/lfo1/s_level',
    '/radiator/color/lfo2/s_level',
    '/radiator/color/lfo3/s_level',
    '/radiator/color/lfo1/v_level',
    '/radiator/color/lfo2/v_level',
    '/radiator/color/lfo3/v_level',
    '/radiator/color/lfo1/mod1',
    '/radiator/color/lfo2/mod1',
    '/radiator/color/lfo3/mod1',
    '/radiator/color/lfo1/mod2',
    '/radiator/color/lfo2/mod2',
    '/radiator/color/lfo3/mod2',
    '/radiator/color/lfo1/mod3',
    '/radiator/color/lfo2/mod3',
    '/radiator/color/lfo3/mod3',
    '/radiator/lfo1/warp',
    '/radiator/lfo2/warp',
    '/radiator/lfo3/warp',
    '/radiator/lfo1/warp_type',
    '/radiator/lfo2/warp_type',
    '/radiator/lfo3/warp_type',
    '/radiator/lfo1/warp_type/name',
    '/radiator/lfo2/warp_type/name',
    '/radiator/lfo3/warp_type/name',
    '/radiator/lfo1/shape',
    '/radiator/lfo2/shape',
    '/radiator/lfo3/shape',
    '/radiator/lfo1/shape/name',
    '/radiator/lfo2/shape/name',
    '/radiator/lfo3/shape/name',
    '/radiator/lfo1/speed',
    '/radiator/lfo2/speed',
    '/radiator/lfo3/speed',
    '/radiator/lfo1/level',
    '/radiator/lfo2/level',
    '/radiator/lfo3/level',
    '/radiator/lfo1/on',
    '/radiator/lfo2/on',
    '/radiator/lfo3/on',
    '/radiator/lfo1/phase',
    '/radiator/lfo2/phase',
    '/radiator/lfo3/phase',
    '/radiator/lfo1/cv1/warp',
    '/radiator/lfo2/cv1/warp',
    '/radiator/lfo3/cv1/warp',
    '/radiator/lfo1/cv1/speed',
    '/radiator/lfo2/cv1/speed',
    '/radiator/lfo3/cv1/speed',
    '/radiator/lfo1/cv1/level',
    '/radiator/lfo2/cv1/level',
    '/radiator/lfo3/cv1/level',
    '/radiator/lfo1/cv4/warp',
    '/radiator/lfo2/cv4/warp',
    '/radiator/lfo3/cv4/warp',
    '/radiator/lfo1/cv4/speed',
    '/radiator/lfo2/cv4/speed',
    '/radiator/lfo3/cv4/speed',
    '/radiator/lfo1/cv4/level',
    '/radiator/lfo2/cv4/level',
    '/radiator/lfo3/cv4/level',
    '/radiator/lfo1/fft_band',
    '/radiator/lfo2/fft_band',
    '/radiator/lfo3/fft_band',
    '/radiator/lfo1/fft_band/name',
    '/radiator/lfo2/fft_band/name',
    '/radiator/lfo3/fft_band/name',
    '/radiator/lfo1/fft_warp',
    '/radiator/lfo2/fft_warp',
    '/radiator/lfo3/fft_warp',
    '/radiator/lfo1/fft_speed',
    '/radiator/lfo2/fft_speed',
    '/radiator/lfo3/fft_speed',
    '/radiator/lfo1/fft_level',
    '/radiator/lfo2/fft_level',
    '/radiator/lfo3/fft_level',
    '/radiator/lfo1/lfo2/warp',
    '/radiator/lfo1/lfo3/warp',
    '/radiator/lfo2/lfo1/warp',
    '/radiator/lfo2/lfo3/warp',
    '/radiator/lfo3/lfo1/warp',
    '/radiator/lfo3/lfo2/warp',
    '/radiator/lfo1/lfo2/speed',
    '/radiator/lfo1/lfo3/speed',
    '/radiator/lfo2/lfo1/speed',
    '/radiator/lfo2/lfo3/speed',
    '/radiator/lfo3/lfo1/speed',
    '/radiator/lfo3/lfo2/speed',
    '/radiator/lfo1/lfo2/level',
    '/radiator/lfo1/lfo3/level',
    '/radiator/lfo2/lfo1/level',
    '/radiator/lfo2/lfo3/level',
    '/radiator/lfo3/lfo1/level',
    '/radiator/lfo3/lfo2/level',
    '/radiator/shapeA/warp',
    '/radiator/shapeA/warp_type',
    '/radiator/shapeA/warp_type/name',
    '/radiator/shapeA/shape',
    '/radiator/shapeA/shape/name',
    '/radiator/shapeA/autorotate_speed',
    '/radiator/shapeA/manual_rotate',
    '/radiator/shapeA/rotate_axis',
    '/radiator/shapeA/rotate_axis/name',
    '/radiator/shapeA/size',
    '/radiator/shapeA/speed',
    '/radiator/shapeA/invert',
    '/radiator/shapeA/autorotate',
    '/radiator/shapeA/on',
    '/radiator/shapeA/lfo1/warp',
    '/radiator/shapeA/lfo2/warp',
    '/radiator/shapeA/lfo3/warp',
    '/radiator/shapeA/lfo1/rotate',
    '/radiator/shapeA/lfo2/rotate',
    '/radiator/shapeA/lfo3/rotate',
    '/radiator/shapeA/lfo1/size',
    '/radiator/shapeA/lfo2/size',
    '/radiator/shapeA/lfo3/size',
    '/radiator/shapeA/lfo1/speed',
    '/radiator/shapeA/lfo2/speed',
    '/radiator/shapeA/lfo3/speed',
    '/radiator/shapeB/warp',
    '/radiator/shapeB/warp_type',
    '/radiator/shapeB/warp_type/name',
    '/radiator/shapeB/shape',
    '/radiator/shapeB/shape/name',
    '/radiator/shapeB/autorotate_speed',
    '/radiator/shapeB/manual_rotate',
    '/radiator/shapeB/rotate_axis',
    '/radiator/shapeB/rotate_axis/name',
    '/radiator/shapeB/size',
    '/radiator/shapeB/speed',
    '/radiator/shapeB/sync',
    '/radiator/shapeB/autorotate',
    '/radiator/shapeB/on',
    '/radiator/shapeB/lfo1/warp',
    '/radiator/shapeB/lfo2/warp',
    '/radiator/shapeB/lfo3/warp',
    '/radiator/shapeB/lfo1/rotate',
    '/radiator/shapeB/lfo2/rotate',
    '/radiator/shapeB/lfo3/rotate',
    '/radiator/shapeB/lfo1/size',
    '/radiator/shapeB/lfo2/size',
    '/radiator/shapeB/lfo3/size',
    '/radiator/shapeB/lfo1/speed',
    '/radiator/shapeB/lfo2/speed',
    '/radiator/shapeB/lfo3/speed',
    '/radiator/trans/warp',
    '/radiator/trans/rotate_offset',
    '/radiator/trans/type',
    '/radiator/trans/type/name',
    '/radiator/trans/source',
    '/radiator/trans/source/name',
    '/radiator/trans/axis_tilt',
    '/radiator/trans/rotate',
    '/radiator/trans/size',
    '/radiator/trans/lfo1/warp',
    '/radiator/trans/lfo2/warp',
    '/radiator/trans/lfo3/warp',
    '/radiator/trans/lfo1/rotate_offset',
    '/radiator/trans/lfo2/rotate_offset',
    '/radiator/trans/lfo3/rotate_offset',
    '/radiator/trans/lfo1/axis_tilt',
    '/radiator/trans/lfo2/axis_tilt',
    '/radiator/trans/lfo3/axis_tilt',
    '/radiator/trans/lfo1/rotation',
    '/radiator/trans/lfo2/rotation',
    '/radiator/trans/lfo3/rotation',
    '/radiator/trans/lfo1/size',
    '/radiator/trans/lfo2/size',
    '/radiator/trans/lfo3/size',
    '/radiator/trans/lfo1/pos_x',
    '/radiator/trans/lfo2/pos_x',
    '/radiator/trans/lfo3/pos_x',
    '/radiator/trans/lfo1/pos_y',
    '/radiator/trans/lfo2/pos_y',
    '/radiator/trans/lfo3/pos_y',
    '/radiator/trans/lfo1/pos_z',
    '/radiator/trans/lfo2/pos_z',
    '/radiator/trans/lfo3/pos_z',
    '/radiator/clone/spread',
    '/radiator/clone/rotate_offset',
    '/radiator/clone/type',
    '/radiator/clone/type/name',
    '/radiator/clone/source',
    '/radiator/clone/source/name',
    '/radiator/clone/speed',
    '/radiator/clone/rotation_x',
    '/radiator/clone/rotation_z',
    '/radiator/clone/lfo1/spread',
    '/radiator/clone/lfo2/spread',
    '/radiator/clone/lfo3/spread',
    '/radiator/clone/lfo1/rotate_offset',
    '/radiator/clone/lfo2/rotate_offset',
    '/radiator/clone/lfo3/rotate_offset',
    '/radiator/clone/lfo1/speed',
    '/radiator/clone/lfo2/speed',
    '/radiator/clone/lfo3/speed',
    '/radiator/clone/lfo1/rotation_x',
    '/radiator/clone/lfo2/rotation_x',
    '/radiator/clone/lfo3/rotation_x',
    '/radiator/clone/lfo1/rotation_z',
    '/radiator/clone/lfo2/rotation_z',
    '/radiator/clone/lfo3/rotation_z',
    '/radiator/master/blackout',
    '/radiator/master/size',
    '/radiator/master/level',
    '/radiator/master/x_scale',
    '/radiator/master/y_scale',
    '/radiator/master/x_offset',
    '/radiator/master/y_offset',
    '/radiator/master/x_flip',
    '/radiator/master/y_flip',
    '/radiator/master/r_level',
    '/radiator/master/g_level',
    '/radiator/master/b_level',
    '/radiator/master/r_bias',
    '/radiator/master/g_bias',
    '/radiator/master/b_bias',
    '/radiator/master/filter',
    '/radiator/master/filter/name',
    '/radiator/master/geocorr/x_keystone',
    '/radiator/master/geocorr/y_keystone',
    '/radiator/master/geocorr/x_bow',
    '/radiator/master/geocorr/y_bow',
    '/radiator/master/geocorr/x_pincushion',
    '/radiator/master/geocorr/y_pincushion',
    '/radiator/master/corner/tl_x',
    '/radiator/master/corner/tl_y',
    '/radiator/master/corner/tr_x',
    '/radiator/master/corner/tr_y',
    '/radiator/master/corner/bl_x',
    '/radiator/master/corner/bl_y',
    '/radiator/master/corner/br_x',
}
